Develop
siblis/pocket-server pull request #6
Opened 2018-09-26 13:07 UTC by kaktycc

Добавлен эхо хендлер, в лог добавлено время

2018-09-27 08:05 UTC, AlwxSin requested changes

2018-09-27 08:05 UTC, AlwxSin commented on handlers/wshandler_echo.py
> +class WebSocketHandlerEcho(tornado.websocket.WebSocketHandler, JsonHandler):
`UserData` и `WebSocketHandlerEcho` практически идентичны обычному хэндлеру.
Почему бы не отнаследоваться?

2018-09-27 08:49 UTC, AlwxSin requested changes

2018-09-27 08:49 UTC, AlwxSin commented on handlers/wshandler_echo.py
> +class WebSocketHandlerEcho(WebSocketHandler):
Но `UserData` тоже надо наследовать. У тебя же был другой `ws_object` в нем.

2018-09-27 08:49 UTC, AlwxSin commented on handlers/wshandler_echo.py
> +    def check_origin(self, origin):
Прочитай про наследование получше. Ты отнаследовался, но все методы скопированы. Зачем?

2018-09-27 10:26 UTC, kaktycc commented on handlers/wshandler_echo.py
> +class WebSocketHandlerEcho(WebSocketHandler):
импортировал, а наследовать не сделал, исправлю

2018-09-29 18:37 UTC, AlwxSin approved these changes

2018-09-29 18:37 UTC, merged