Develop
siblis/pocket-server pull request #7
Opened 2018-10-03 11:44 UTC by kaktycc

Добавлено время жизни токена, исправлен формат сообщений в WS, удалено лишнее в кодах ответа

2018-10-03 15:12 UTC, kaktycc commented
Наверное все-таки поле tokenexp надо сделать datetime, а не string

2018-10-05 09:32 UTC, AlwxSin requested changes

2018-10-05 09:32 UTC, AlwxSin commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Вообще, время жизни токена обычно передают не строкой или `datetime`, а таймштампом.

2018-10-08 10:12 UTC, kaktycc commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Сколько не мучался не получается таймштампом добавить, нашел ссылку по типам
[http://initd.org/psycopg/docs/usage.html#adaptation-of-python-values-to-sql-types]
написано datetime питона соответствует timestamp postgres

2018-10-11 07:52 UTC, AlwxSin commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Ага, я тебя понял. Тут есть пара "но":
* Как время хранится в БД и как оно показывается - две большие разницы.
* Мы можем хранить в БД как стандартный `datetime`, а вот при записи в токен переводить его в `timestamp`

2018-10-11 07:53 UTC, AlwxSin commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Собственно, ты уже его правильно хранишь. Осталось только изменить формат его выдачи.

2018-10-11 07:56 UTC, AlwxSin requested changes

2018-10-11 07:56 UTC, AlwxSin commented on handlers/contactshandler.py
> +        JsonHandler.prepare(self)
Непонятно, что здесь имеется ввиду.
Если вызов метода из родительского класса, то нужно делать так `super().prepare(self)`

2018-10-12 10:59 UTC, kaktycc commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Выдачи это то есть формат когда "вытаскиваю" из таблицы?
Получается из таблицы забираем строку и преобразуем в таймштамп или не в так думаю?

2018-10-16 09:01 UTC, AlwxSin commented on handlers/json_util.py
> +        token_expire = (today + days).strftime("%Y-%m-%d %H:%M:%S")
Да, именно так. Только в БД оно хранится не в виде строки, а в типе датавремя.

2018-10-16 09:01 UTC, AlwxSin approved these changes

2018-10-16 09:01 UTC, merged